### ISSUE TITLE
Running NLI_KD_training.py raises the following error.

### ISSUE THREAD

**Issue by non-swimmer** [intersun/PKD-for-BERT-Model-Compression#1]
File 'NLI_KD_training.py',line 204, max_grad_norms=1.0)
TypeError: init() got an unexpected keyword argument 'max_grad_norm=1.0'
According to https://nvidia.github.io/apex/optimizers.html, the apex has been updated to  a new release that removed this parameter. If just ignore this parameters, will the performance be influenced?

**Comment by intersun** [comment]
apex updates so often that this might fail... 

Can you try below command and see if it works?

git clone https://github.com/NVIDIA/apex
cd apex
git reset --hard 3d01e4a0a188cc8df54bc6e44cf5eb40ff6b4cc5
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .

**Comment by intersun** [comment]
I will close this issue for now, if you still have problems feel free to reopen it :)

Thanks.
