### ISSUE TITLE
Where to download the pretrained weights?

### ISSUE THREAD

**Issue by thudzj** [intersun/PKD-for-BERT-Model-Compression#2]
Thanks a lot for your impressive work and I want to reproduce the results in the paper. Now I have a question: where can I get the pretrained model (bert-base-uncased)? Thank you!

**Comment by intersun** [comment]
Thanks for your comments. 
You can find pre-trained language models here from line 37 to 53.
https://github.com/huggingface/transformers/blob/f62f992cf7aa7f1e4eb0d1ef912bd06d26c4dd8c/transformers/modeling_bert.py

Please reopen this issue if you find more problems.
