### ISSUE TITLE
question on pretrained/bert_config.json

### ISSUE THREAD

**Issue by Seohyeong** [intersun/PKD-for-BERT-Model-Compression#3]
Thanks for sharing your work! I'm training a new dataset (classification task just like glue dataset) with following steps and wanted to make sure whether I'm doing it right.

1. get finetuned BERT (pytorch_model.bin) on dataset and put it into pretrained directory

2. run NLI_KD_training.py with below to get encoder.pkl, classifier.pkl
```
# run simple fune-tuning *teacher* by uncommenting below cmd
argv = get_predefine_argv('glue', 'RTE', 'finetune_teacher')
```

3. run run_glue_benchmark.py to get teacher's prediction for KD

4. run NLI_KD_training.py with below to distil knowledge from teacher to student model
```
    # run Patient Teacher by uncommenting below cmd
    argv = get_predefine_argv('glue', 'RTE', 'kd.cls')
```

I'm confused since doing step 2 redundantly finetunes teacher (bert base model) which was already done in step 1. Is it correct to place finetuned version into pretrained directory? or should I just use plain pytorch_model.bin?

**Comment by intersun** [comment]
Thanks for pointing that out.  The first step should be
"1. get **pre-trained** BERT (pytorch_model.bin) on dataset and put it into pretrained directory" instead of fine-tuned one.

Please re-open the issue or reply here if you find any other issue.

**Comment by smr97** [comment]
I ran the NLI_KD_training.py script and didn't get any pickles for encoder and classifier. I uncommented the same line that OP mentions. PLease help
