### ISSUE TITLE
What's the version of python and pytorch of this project?

### ISSUE THREAD

**Issue by vikotse** [intersun/PKD-for-BERT-Model-Compression#4]
I am Impressed by your crucial work. But I encounter some issues when I reproduce this project, may I ask a question that: What's the version of python and pytorch of this project?

**Comment by intersun** [comment]
Thanks for your interests. 

when I developed this project I used pytorch 1.0 and python 3.6. And it should work with pytorch 1.1 as well. 

Please reopen the issue if you have more questions.

Thanks,

Siqi
