### ISSUE TITLE
How do I run student predictions?

### ISSUE THREAD

**Issue by smr97** [intersun/PKD-for-BERT-Model-Compression#7]
Hey, I am trying to reproduce your results, and am interested in training several students with different number of hidden layers. I want to submit the student predictions on GLUE website. I have been able too train student models with PKD-skip procedure.

My question is, how do I make predictions from the student model? I guess I should change the run_glue_benchmark somehow. Any help in this regard will be appreciated.

**Comment by intersun** [comment]
the script is designed based on my folder structure, the core code should be as below (starts from line 111)

initialized your model with your trained model files
```
encoder_file, cls_file = encoder_file[0], cls_file[0]                # your trained encoder and cls file
encoder_bert, classifier = init_model(task, output_all_layers, n_layer, config)  
encoder_bert = load_model(encoder_bert, encoder_file, args, 'exact', verbose=True)
classifier = load_model(classifier, cls_file, args, 'exact', verbose=True)
```

and load and make prediction (starts from line 119)

```
dev_examples, dev_dataloader, dev_label_ids = get_task_dataloader(task.lower(), 'dev', tokenizer, args, SequentialSampler, args.eval_batch_size)
dev_res = eval_model_dataloader(encoder_bert, classifier, dev_dataloader, args.device, detailed=True, verbose=False)    
dev_pred_label = dev_res['pred_logit'].argmax(1) 
logger.info('for dev, acc = {}, loss = {}'.format(dev_res['acc'], dev_res['loss'])) 
logger.info('debug dev acc = {}'.format((dev_label_ids.numpy() == dev_pred_label).mean()))
```

Please let me know if it works.

Thanks for your interests.

**Comment by smr97** [comment]
Thank you, it works!
