### ISSUE TITLE
Trying to do distillation for regression task

### ISSUE THREAD

**Issue by smr97** [intersun/PKD-for-BERT-Model-Compression#8]
Hi, I am trying to extend your research and compute accuracy for all GLUE tasks, in that I am kind of stuck with STS-B. Since it is a regression task, where all do you think I should make the changes to get the numbers?

**Comment by intersun** [comment]
Intuitively it should be the same, just change cross entropy loss to regression loss (typically MSE), and everything else remains the same. 

Please leave a comment or reopen the issue if you still have any questions.
